version: '3.2'
services:
  # POSTGRES
  postgres:
    image: postgres:10-alpine
    networks:
      - skelleton
    ports:
      - 8001:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  # REDIS
  redis:
    image: redis:latest
    networks:
      - skelleton
    ports:
      - 8002:6379
  # scraper
  scraper:
    image: skelleton:latest
    networks:
      - skelleton
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/scraper.env
    environment:
      - APP=scraper
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - REDIS_URL=redis://redis
    depends_on:
      - postgres
      - redis


networks:
  skelleton:
